#! python

from random import choice
import sys

vidas = 6
palabra_secreta = ''
palabra_oculta = ''

def seleccionar_palabra():
    '''
    Esta funcion sirve para seleccionar al 
    azar una palabra de la lista
    '''
    lista_palabras = ['entretenimiento','television','pelicano','onomatopella','cuadrante']
    return choice(lista_palabras)

def ocultar_palabra(palabra):
    '''
    Esta funcion recibe una palabra como argumento
    Devuelve una cadena de guiones por cada letra
    que contenga esa palabra
    '''
    palabra_oculta = ''
    print(palabra)
    for letra in palabra:
        palabra_oculta += '_'    
    return palabra_oculta        
    
def validar_letra(letra):
    '''
    Esta funcion procesa la letra que ingresa el usuario
    Si la letra no se encuentra en el abecedario
    vuelve a pedir otra letra
    Si la letra ingresada esta en el abecedario, devuelve letra
    '''
    abecedario = [chr(i) for i in range(ord('a'), ord('z') + 1)]
    if letra not in abecedario:
        print('Caracter no válido.')
        return False
    else:
        return True
    
def comprobar_letra(letra):
    '''
    Esta funcion va comprobar si la letra ingresada
    por el usuario se encuentra en la palabra secreta
    '''
    letras_equivocadas = []
    palabra = palabra_secreta
    if letra not in palabra_secreta:
        letras_equivocadas.append(letra)
        vidas -= 1
        print(f'''Te equivocaste.
            {letras_equivocadas}
            Te quedan {vidas} vidas.''')
    else:
        for n in palabra_secreta:
            if n != letra:
                palabra.replace(n,'_')
        return palabra
        
while True:
    print('EL JUEGO DEL AHORCADO')
    palabra_secreta = seleccionar_palabra()
    palabra_oculta = ocultar_palabra(palabra_secreta)
    print(f'''Cuentas con 6 vidas para adivinar qué palabra es esta: 
    {palabra_oculta}''')
    while vidas >= 1:
        letra = input('Introduce una letra: ')
        while validar_letra(letra):
            comprobar_letra(letra)
            break
        # print(comprobar_letra(validar_letra()))
        
#for n in palabra:
#     if letra != n:
#         palabra = palabra.replace(n,'_')
