#! python

from random import choice

'''
EL JUEGO DEL AHORCADO
- El programa va elegir una palabra secreta
- Mostrara una serie de guiones por cada letra de la palabra
- Si el jugador dice una letra, el programa reemplaza
el guion por la letra si la palabra la contiene
- Se tendran 6 vidas antes de perder para adivinar la palabra
- Importar el metodo choice
- Crear funciones para cada proceso por separado
    pedir letra
    validar letra
    chequear letra
    ver si gano
- Escribir primero als funciones y luego el codigo que
las implementa


- Para la seleccion de la palabra se usara un diccionario
predefinido con ciertos valores por selecionar
- La salida de la funcion que seleccione la palabra sera
la entrada de la funcion que pida la letra


- Funcion para elegir una palabra
- Funcion para preguntar y comprobar letra
- Funcion para mostrar letra en palabra
- Funcion para comprobar si gano
'''
palabra_secreta = ''
palabra_oculta = ''

def seleccionar_palabra():
    '''
    Esta funcion sirve para seleccionar al 
    azar una palabra de la lista
    '''
    lista_palabras = ['entretenimiento','television','pelicano','onomatopella','cuadrante']
    return choice(lista_palabras)

def ocultar_palabra(palabra):
    '''
    Esta funcion recibe una palabra como argumento
    Devuelve una cadena de guiones por cada letra
    que contenga esa palabra
    '''
    palabra_oculta = ''
    print(palabra)
    for letra in palabra:
        palabra_oculta += '_'    
    return palabra_oculta
    
def comprobar_letra(letra,palabra_secreta,palabra_oculta):
    '''
    Esta funcion recibe 3 argumentos
    - La letra que ingresa el usuario
    - La palabra al azar
    - La palabra oculta
    Verrifica si la letra ingresada se encuentra en la palabra
    Si es asi, reemplaza en la palabra oculta las letras
    '''
    cuenta = 0
    for n in palabra_secreta:
        if letra != n:
            cuenta += 1
            pass
        elif letra == n:
            palabra_guion = palabra_oculta.replace('_',n)
            cuenta += 1
        else:
            cuenta += 1
    return palabra_guion

print('EL JUEGO DEL AHORCADO')
palabra_secreta = seleccionar_palabra()
palabra_oculta = ocultar_palabra(palabra_secreta)
print(f'''Cuentas con 6 vidas para adivinar qué palabra es esta: 
{palabra_oculta}''')
letra = str(input('Ingresa una letra: '))
print(comprobar_letra(letra,palabra_secreta,palabra_oculta))
